const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const contentFile = path.join(root, "content", "million-dollar-receipt.json");
const outputFile = path.join(root, "assets", "js", "mdr-config.js");

function hasText(value) {
  return typeof value === "string" && value.trim().length > 0;
}

function assertArray(value, label) {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array.`);
  }
}

function validateMdr(data) {
  const errors = [];

  if (!data || typeof data !== "object") {
    errors.push("Million Dollar Receipt content must be an object.");
    return { errors };
  }

  ["title", "tagline"].forEach((field) => {
    if (!hasText(data[field])) {
      errors.push(`${field} is required.`);
    }
  });

  if (!Number.isInteger(data.goalCount) || data.goalCount <= 0) {
    errors.push("goalCount must be a positive integer.");
  }

  if (!Number.isInteger(data.priceCents) || data.priceCents <= 0) {
    errors.push("priceCents must be a positive integer.");
  }

  try {
    assertArray(data.tiers, "tiers");
    assertArray(data.milestones, "milestones");
    assertArray(data.faq, "faq");
    assertArray(data.howItWorks, "howItWorks");
    assertArray(data.mockReceipts, "mockReceipts");
  } catch (error) {
    errors.push(error.message);
  }

  if (!data.legal || typeof data.legal !== "object") {
    errors.push("legal is required.");
  }

  if (!data.mockStats || typeof data.mockStats !== "object") {
    errors.push("mockStats is required.");
  }

  return { errors };
}

function loadMdr() {
  return JSON.parse(fs.readFileSync(contentFile, "utf8"));
}

function buildMdr() {
  const data = loadMdr();
  const result = validateMdr(data);

  if (result.errors.length) {
    const error = new Error(`Million Dollar Receipt validation failed:\n- ${result.errors.join("\n- ")}`);
    error.validation = result;
    throw error;
  }

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(
    outputFile,
    `/* Generated by scripts/build-mdr.js. Do not edit directly; update content/million-dollar-receipt.json and rebuild. */\nwindow.mdrConfig = ${JSON.stringify(data, null, 2)};\n`
  );

  return { outputFile, data };
}

if (require.main === module) {
  const result = buildMdr();
  console.log(`Built ${path.relative(root, result.outputFile).replace(/\\/g, "/")}`);
}

module.exports = {
  contentFile,
  outputFile,
  loadMdr,
  validateMdr,
  buildMdr
};
