window.LEMONTEED_FM_TRACKS = [
  {
    "id": "lemonteed-fm-93-7-internet-s-least-funded-booth",
    "title": "Internet's Least Funded Booth",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "station-id",
    "mood": "late-night editing",
    "vibe": [
      "intro",
      "station dj"
    ],
    "tags": [
      "lemonteedfm"
    ],
    "duration": "1:12",
    "durationSec": 72,
    "artworkSmall": "/images/lemonteed-fm/lemonteed-fm-93-7-internet-s-least-funded-booth-480.webp",
    "artworkLarge": "/images/lemonteed-fm/lemonteed-fm-93-7-internet-s-least-funded-booth.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/internets-least-funded-booth.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/the_lemon_is_strong",
    "license": "All Rights Reserved",
    "attribution": "Internet's Least Funded Booth by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "The booth theme. The signal that tells you something mildly unusual is about to happen.",
    "program": "Internet's Least Funded Booth",
    "addedDate": "2025-11-04",
    "featured": true,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "impressions-before-coffee",
    "title": "Impressions Before Coffee",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "lo-fi",
    "mood": "lo-fi focus",
    "vibe": [
      "lofi"
    ],
    "tags": [],
    "duration": "2:34",
    "durationSec": 154,
    "artworkSmall": "/images/lemonteed-fm/impressions-before-coffee-480.webp",
    "artworkLarge": "/images/lemonteed-fm/impressions-before-coffee.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/impressions_before_coffee.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/impressions-before-coffee",
    "license": "All Rights Reserved",
    "attribution": "Impressions Before Coffee by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "Dusty morning loops for work that should have been finished yesterday.",
    "program": "Internet's Least Funded Booth",
    "addedDate": "2025-12-01",
    "featured": false,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "dance-for-legal-s-sake",
    "title": "Dance For Legal's Sake",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "corporate-satire",
    "mood": "corporate menace",
    "vibe": [
      "corporate dance-pop",
      "corporate satire"
    ],
    "tags": [],
    "duration": "1:27",
    "durationSec": 87,
    "artworkSmall": "/images/lemonteed-fm/dance-for-legal-s-sake-480.webp",
    "artworkLarge": "/images/lemonteed-fm/dance-for-legal-s-sake.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/dance_for_legals_sake.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/dance-for-legals-sake",
    "license": "All Rights Reserved",
    "attribution": "Dance For Legal's Sake by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "A compliance anthem for teams that forgot fun was optional.",
    "program": "Songs the Algorithm Forgot",
    "addedDate": "2025-12-08",
    "featured": false,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "monopoly-is-the-condition-of-every-business",
    "title": "Monopoly Is The Condition Of Every Business",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "novelty-rap",
    "mood": "quiet panic",
    "vibe": [
      "90s Monopoly Rap",
      "Peter Thiel"
    ],
    "tags": [],
    "duration": "2:33",
    "durationSec": 153,
    "artworkSmall": "/images/lemonteed-fm/monopoly-is-the-condition-of-every-business-480.webp",
    "artworkLarge": "/images/lemonteed-fm/monopoly-is-the-condition-of-every-business.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/monopoly-is-the-condition-of-every-successful-business-compressed.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/monopoly-business",
    "license": "All Rights Reserved",
    "attribution": "Monopoly Is The Condition Of Every Business by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "Inspired by a quote that sounds like a threat but got a book deal instead.",
    "program": "Songs the Algorithm Forgot",
    "addedDate": "2026-01-15",
    "featured": false,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "turn-the-lemon-dial",
    "title": "Turn the Lemon Dial",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "synthwave",
    "mood": "midnight radio",
    "vibe": [
      "synthwave",
      "midnight radio"
    ],
    "tags": [],
    "duration": "1:40",
    "durationSec": 100,
    "artworkSmall": "/images/lemonteed-fm/turn-the-lemon-dial-480.webp",
    "artworkLarge": "/images/lemonteed-fm/turn-the-lemon-dial.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/turn-the-lemon-dial.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/turn-the-lemon-dial",
    "license": "All Rights Reserved",
    "attribution": "Turn the Lemon Dial by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "The station's unofficial closing theme. Works best at 1 AM with the brightness down.",
    "program": "Midnight Lemon Dial",
    "addedDate": "2026-01-22",
    "featured": false,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "trust-me-bro",
    "title": "Trust Me Bro",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "garage-rock",
    "mood": "late-night editing",
    "vibe": [
      "punky garage rock",
      "chaotic internet anthem"
    ],
    "tags": [],
    "duration": "2:32",
    "durationSec": 152,
    "artworkSmall": "/images/lemonteed-fm/trust-me-bro-2-480.webp",
    "artworkLarge": "/images/lemonteed-fm/trust-me-bro-2.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/trust-me-bro.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/trust_me_bro",
    "license": "All Rights Reserved",
    "attribution": "Trust Me Bro by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "The official anthem of every pitch deck that did not include a source.",
    "program": "Songs the Algorithm Forgot",
    "addedDate": "2026-02-05",
    "featured": false,
    "canHost": true,
    "canDownload": false
  },
  {
    "id": "track-seven",
    "title": "Track Seven",
    "artist": "Lemonteed FM",
    "album": "Station Originals",
    "genre": "indie-pop",
    "mood": "quiet panic",
    "vibe": [
      "sad indie pop",
      "lo-fi bedroom music"
    ],
    "tags": [],
    "duration": "2:41",
    "durationSec": 161,
    "artworkSmall": "/images/lemonteed-fm/track-seven-480.webp",
    "artworkLarge": "/images/lemonteed-fm/track-seven.webp",
    "previewAudio": "",
    "fullAudio": "/images/lemonteed-fm/audio/track-seven.mp3",
    "sourceName": "SoundCloud",
    "sourceUrl": "https://soundcloud.com/lemonteedfm/track-seven",
    "license": "All Rights Reserved",
    "attribution": "Track Seven by Lemonteed FM. All Rights Reserved.",
    "usage": "Verify the original source before using in any project. This track is not licensed for reuse.",
    "curatorNote": "Named Track Seven because that is what the file was called and nothing better came to mind.",
    "program": "Midnight Lemon Dial",
    "addedDate": "2026-03-01",
    "featured": false,
    "canHost": true,
    "canDownload": false
  }
];
